services:
  web:
    container_name: webserver
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - e-document-service
    volumes:
      - ./frontend/build:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
    networks:
      - e_document_ci_cd_net
  e-document-service:
    image: acework2u/e-document-service:latest
    container_name: e-document-service
    ports:
      - "8088:8088"
    volumes:
      - ./conf:/app/conf
      - ~/.aws/:/root/.aws:ro
    links:
      - database
    depends_on:
      - database
    networks:
      - e_document_ci_cd_net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGURI}
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      ME_CONFIG_MONGODB_SERVER: 'e-document-mongodb'
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:172.19.0.1"
  database:
    container_name: e-document-mongodb
    image: mongo:latest
    hostname: e-document-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:27017
    networks:
      - e_document_ci_cd_net
    volumes:
      - ./mongo_config/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./mongo_config/mongod.conf:/etc/mongo/mongod.conf
      #      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./mongo_data:/data/db
    command: mongod --config /etc/mongo/mongod.conf
volumes:
  db-data:
  mongodb_data_smartapp:

networks:
  e_document_ci_cd_net:
    driver: bridge
    name: e_document_ci_cd_net