name: Deploy to Application

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t acework2u/line-medical-volunteer -f prod.Dockerfile .
      - name: Push image to Docker Hub
        run: docker push acework2u/line-medical-volunteer:latest
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull acework2u/line-medical-volunteer:latest
      - name: Delete old container
        run: docker rm -f line-medical-volunteer
      - name: Run Docker container
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          cd ~/line-medical-app/  # Adjust to match the path containing docker-compose.yml
          docker compose down              # Stop running containers
          docker compose pull              # Pull the latest image from Docker Hub
          docker compose up -d             # Run containers with the latest image
