name: Deploy to Production

on:
  push:
    branches:
      - deploy-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT-${{secrets.PORT}}" >> .env
      - name: login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t acework2u/line-medical-volunteer -f prod.Dockerfile .
      - name: Push image to Docker Hub
        run: docker push acework2u/line-medical-volunteer:latest

  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull acework2u/line-medical-volunteer:latest
      - name: Delete old container
        run: docker rm -f line-medical-volunteer
      - name: Run Docker container
        run: |
          set -e #Exit immediately if a command exits with a non-zero status
          cd ~/line-medical-app/ # this edit path have to docker-compose.yml
          docker compose down
          docker compose pull
          docker compose up -d